services:
  backend:
    build: ./Backend
    restart: always
    depends_on: 
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./Frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"
    
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: base_popcorn
      MYSQL_ROOT_PASSWORD: mais
      MYSQL_USER: popcorn
      MYSQL_PASSWORD: mais
    ports:
      - 3306:3306
    ##############
    volumes:
      - mariadb:/database
      
##############
volumes: 
  mariadb:

